prebuilt_jar(name='commons-lang3', binary_jar=':commons-lang3-mvn', visibility=['PUBLIC'])

remote_file(name='commons-lang3-mvn', out='commons-lang3-3.5.jar', url='mvn:org.apache.commons:commons-lang3:jar:3.5', sha1='6c6c702c89bfff3cd9e80b04d668c5e190d588c6')
